pub const LAT_CYRILLIC: [(char, char); 54] = [
    ('A', 'А'),
    ('B', 'Б'),
    ('V', 'В'),
    ('G', 'Г'),
    ('D', 'Д'),
    ('Đ', 'Ђ'),
    ('E', 'Е'),
    ('Ž', 'Ж'),
    ('Z', 'З'),
    ('I', 'И'),
    ('J', 'Ј'),
    ('K', 'К'),
    ('L', 'Л'),
    ('M', 'М'),
    ('N', 'Н'),
    ('O', 'О'),
    ('P', 'П'),
    ('R', 'Р'),
    ('S', 'С'),
    ('T', 'Т'),
    ('Ć', 'Ћ'),
    ('U', 'У'),
    ('F', 'Ф'),
    ('H', 'Х'),
    ('C', 'Ц'),
    ('Č', 'Ч'),
    ('Š', 'Ш'),
    ('a', 'а'),
    ('b', 'б'),
    ('v', 'в'),
    ('g', 'г'),
    ('d', 'д'),
    ('đ', 'ђ'),
    ('e', 'е'),
    ('ž', 'ж'),
    ('z', 'з'),
    ('i', 'и'),
    ('j', 'ј'),
    ('k', 'к'),
    ('l', 'л'),
    ('m', 'м'),
    ('n', 'н'),
    ('o', 'о'),
    ('p', 'п'),
    ('r', 'р'),
    ('s', 'с'),
    ('t', 'т'),
    ('ć', 'ћ'),
    ('u', 'у'),
    ('f', 'ф'),
    ('h', 'х'),
    ('c', 'ц'),
    ('č', 'ч'),
    ('š', 'ш'),
];

pub const CYRILLIC_LAT: [(char, &'static str); 60] = [
    ('А', "A"),
    ('Б', "B"),
    ('В', "V"),
    ('Г', "G"),
    ('Д', "D"),
    ('Ђ', "Đ"),
    ('Е', "E"),
    ('Ж', "Ž"),
    ('З', "Z"),
    ('И', "I"),
    ('Ј', "J"),
    ('К', "K"),
    ('Л', "L"),
    ('Љ', "Lj"),
    ('М', "M"),
    ('Н', "N"),
    ('Њ', "Nj"),
    ('О', "O"),
    ('П', "P"),
    ('Р', "R"),
    ('С', "S"),
    ('Т', "T"),
    ('Ћ', "Ć"),
    ('У', "U"),
    ('Ф', "F"),
    ('Х', "H"),
    ('Ц', "C"),
    ('Ч', "Č"),
    ('Џ', "Dž"),
    ('Ш', "Š"),
    ('а', "a"),
    ('б', "b"),
    ('в', "v"),
    ('г', "g"),
    ('д', "d"),
    ('ђ', "đ"),
    ('е', "e"),
    ('ж', "ž"),
    ('з', "z"),
    ('и', "i"),
    ('ј', "j"),
    ('к', "k"),
    ('л', "l"),
    ('љ', "lj"),
    ('м', "m"),
    ('н', "n"),
    ('њ', "nj"),
    ('о', "o"),
    ('п', "p"),
    ('р', "r"),
    ('с', "s"),
    ('т', "t"),
    ('ћ', "ć"),
    ('у', "u"),
    ('ф', "f"),
    ('х', "h"),
    ('ц', "c"),
    ('ч', "č"),
    ('џ', "dž"),
    ('ш', "š"),
];

pub const LITERAL_PREFIXES: [&'static str; 44] = [
    "anjon",
    "adjektiv",
    "adjunkt",
    "budzašto",
    "vanjezič",
    "injekt",
    "injekc",
    "konjug",
    "konjunk",
    "nadždrel",
    "nadžet",
    "nadžive",
    "nadživ",
    "nadžnje",
    "nadžup",
    "nadjača",
    "nadjaha",
    "odžali",
    "odžari",
    "odžvaka",
    "odžubor",
    "odžive",
    "odživlj",
    "odjav",
    "odjaha",
    "odjaš",
    "odjeb",
    "odjedri",
    "odjezdi",
    "odjedanput",
    "odjedared",
    "odjednom",
    "odjek",
    "odjeci",
    "odjur",
    "podžanr",
    "podjar",
    "podjamči",
    "podjezič",
    "podjednak",
    "predživot",
    "predželuda",
    "predjel",
    "tanjug",
];

pub const IJEKAVIAN_PREFIXES: [&'static str; 50] = [
    "podjel",
    "hljeb",
    "djevo",
    "dječ",
    "djec",
    "djevi",
    "razdjev",
    "djever",
    "djeli",
    "djelo",
    "zdjel",
    "bdje",
    "bludj",
    "vidje",
    "drvodjelj",
    "drugdje",
    "žudje",
    "zavidj",
    "zlodjel",
    "igdje",
    "lebdje",
    "nadjev",
    "nadjenul",
    "nadjenut",
    "negdje",
    "nedjelj",
    "nenavidj",
    "nigdje",
    "ovdje",
    "odjel",
    "odjev",
    "odjeć",
    "ondje",
    "opredje",
    "ponedjelj",
    "prdje",
    "razdjel",
    "razodj",
    "raspodj",
    "svagdje",
    "smrdj",
    "usmrdj",
    "sudjel",
    "usidjelic",
    "uštedjeti",
    "uštedjeo",
    "uštedjela",
    "uštedjeli",
    "gdje",
    "djelov",
];
